name: Build/test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: ['temurin']
        java: [8, 11, 17, 21, 25]
      fail-fast: false
    name: JDK ${{ matrix.java }} (${{ matrix.distribution }})

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up JDK
      uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Test with Maven
      run: ./mvnw test -B --file pom.xml
