name: Build/test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: ['temurin']
        java: [8, 11, 17, 21, 25]
      fail-fast: false
    name: JDK ${{ matrix.java }} (${{ matrix.distribution }})

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Set up JDK
      uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Test with Maven
      run: mvn verify -B --file pom.xml
